### ISSUE TITLE
Prepare deploy to production

### ISSUE THREAD

**Issue by Poliuk** [worona/worona-pwa#24]
- [x] Configure now
- [x] Configure keycdn

**Comment by luisherranz** [comment]
- [x] Get rid of babel-modules first because the build fails.
- [x] Figure out a way to keep using different git repositories but keep everything in sync with the deployed version.
- [ ] Figure out a way to be able to have different (less packages) development versions.
- [x] Figure out a way to do the final deploys with correct git versions for each packages.

**Comment by luisherranz** [comment]
Got rid using env-cmd.

**Comment by luisherranz** [comment]
Working now on https://prepwa.worona.org <- BUT DO NOT USE A SITE WITH ADSLZONE URL!
